config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  devise_for :admins, :controllers => { :sessions => "admins/sessions" }

  root to: 'tests#index'

  resources :badges, only: :index

  resources :tests, only: :index do
    resources :questions, shallow: :true

    member do
      post :start
    end
  end

  resources :feedbacks, only: [:create, :new]

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions do
        resources :answers
      end
    end

    resources :gists, only: :index
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :gists, dependent: :destroy
  has_many :answers, dependent: :destroy

  validates :body, presence: true

end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: [:index, :create, :new, :edit]
  before_action :find_question, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def index
    @collection = @test.questions
  end

  def show
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to admin_test_questions_path
    else
      render :edit
    end
  end

  def new
    @question = Question.new
  end

  def create
    @question = @test.questions.new(question_params)

    if @question.save
      redirect_to admin_test_questions_path(@test)
    else
      render :new
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_test_questions_path
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: 'Question was not found'
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      'Edit question'
    else
      'Create new question'
    end
  end

end

app/views/questions/_form.html.erb
<%= question_header(@question) %>
<%= form_with model: @question do |form| %>
  <%= render 'shared/errors', resource: @question %>

  <p>
  <%= form.label :body %> <br>
  <%= form.text_field :body %>
  </p><br>

  <p><%= form.submit %></p>
<% end %>

app/views/questions/edit.html.erb
<%= render 'form' %>
<%= link_to 'Back', admin_test_questions_path(@test.id) %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<p>
  <%= link_to 'New question', new_test_question_path %>
</p>

<table>
    <tr>
      <th>Tests id</th>
      <th>Questions</th>
      <th cosplain="3">Actions</th>
    </tr>
  <% @collection.each do |question| %>
    <tr>
      <td><%=@test.id%></td>
      <td><%= question.body %></td>
      <td><%= link_to 'Show', question_path(question) %></td>
      <td><%= link_to 'Edit', edit_question_path(question) %></td>
    </tr>
  <% end %>
</table>

app/views/questions/new.html.erb
<%= render 'form'%>
<%= link_to 'Back', admin_test_question_path %>

app/views/questions/show.html.erb
<%= @question.body %>
<%= link_to 'Edit', admin_edit_question_path(@question) %>
<%= link_to 'Back', test_questions_path(@question) %>