config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  devise_for :admins, :controllers => { :sessions => "admins/sessions" }

  root to: 'tests#index'

  resources :badges, only: :index

  resources :tests, only: :index do
    resources :questions, shallow: :true

    member do
      post :start
    end
  end

  resources :feedbacks, only: [:create, :new]

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions do
        resources :answers
      end
    end

    resources :gists, only: :index
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :gists, dependent: :destroy
  has_many :answers, dependent: :destroy

  validates :body, presence: true

end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  CHECK_NUMBER = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  # validates :current_question, presence: true

  before_validation :before_validation_set_current_question, on: :create

  scope :tests_by_level, -> (level) {
      joins(:test).where('tests.level = ?', level)
    }

  def completed?
    current_question.nil?
  end

  def expired?
    timing <= 0
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    self.current_question = next_question
    save!
  end

  def correct_answers
    current_question.answers.correct
  end

  def all_questions
    all_questions = test.questions
  end

  def success?
    count_true_answers >= CHECK_NUMBER
  end

  def count_true_answers
    self.correct_questions.to_f / test.questions.count * 100
  end

  def timing
    @start_time = self.created_at
    @spend_time = Time.now.to_i - @start_time.to_i
    time_left = self.test.time.to_i - @spend_time.to_i / 60
  end

  private

  def before_validation_set_current_question
    self.current_question = all_questions.first if test.present?
  end

  def next_question
    x = all_questions.find_index(current_question)
    all_questions[x + 1]
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count
    (correct_answers_count == correct_answers.where(id: answer_ids).count)
  end

end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :find_test_passage, only: [:show, :update, :result, :gist]

  def show
    @test_passage.timing
  end

  def result
  end

  def update
    @test_passage.accept!(params[:answer_ids])
    if @test_passage.completed? || @test_passage.expired?
      # TestsMailer.completed_test(@test_passage).deliver_now
      badge_service = BadgeService.new(current_user, @test_passage)
      badge_service.badge_push
      redirect_to result_test_passage_path(@test_passage)
    else
      redirect_to test_passage_path(@test_passage)
    end
  end

  def gist
    service = GistQuestionService.new(@test_passage.current_question)
    result = service.call
    if service.success?
      Gist.create(user_id: @test_passage.user.id, question_id: @test_passage.current_question.id, gist_remote_id: result.id )
      flash[:notice] = t('.success') + ' ' + result.html_url
    else
      flash[:alert] = t.('failure')
    end

    redirect_to @test_passage
  end

  private

  def continue_test
    @test_passage.accept!(params[:answer_ids])
  end

  def find_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def set_style
    if @test_passage.success?
      "<p style='color:green'> #{@test_passage.count_true_answers} </p><p>You passed the test</p>"
    else
      "<p style='color:red'> #{@test_passage.count_true_answers} </p><p>You did not passed the test</p>"
    end
  end

end

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>
<p><%= set_style.html_safe %></p>
<p><%=link_to 'Tests', tests_path %></p>

app/views/test_passages/show.html.erb
<% arr = @test_passage.all_questions.order(id: :asc) %>
<%= arr.index{ |x| x[:id] == @test_passage.current_question.id} + 1 %>/<%= @test_passage.all_questions.count %>

<div class="progress">
  <%= content_tag :div,
                class: 'progress-bar bg-success',
                role: "progressbar",
                data: { count: @test_passage.all_questions.count,
                current: @test_passage.current_question.id },
                style: "width: 0%" do %>
                <% end %>
</div>
<p>
  <b><%= @test_passage.current_question.body %></b>
</p>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>
  <p id="minute"> <%= @test_passage.test.time.to_i - ((Time.now - @test_passage.created_at).to_f / 60) %></p><p id="second"> </p>

  <p><%= link_to 'Gist Question', gist_test_passage_path(@test_passage), method: :post %></p>
  <p><%= form.submit 'Next' %></p>
<%end%>