config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  devise_for :admins, :controllers => { :sessions => "admins/sessions" }

  root to: 'tests#index'

  resources :badges, only: :index

  resources :tests, only: :index do
    resources :questions, shallow: :true

    member do
      post :start
    end
  end

  resources :feedbacks, only: [:create, :new]

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions do
        resources :answers
      end
    end

    resources :gists, only: :index
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validate :max_answers
  validates :body, presence: true

  def max_answers
    errors.add(:base, "exceeds the maximum value of answers") if question.answers.count >= 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :find_test, only: [:index, :create, :new, :edit]
  before_action :find_question, only: [:index, :show, :edit, :new, :create]
  before_action :find_answer, only: [:show, :edit, :update, :destroy]

  def index
    @collection = @question.answers
  end

  def show
  end

  def edit
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_test_question_answers_path
    else
      render :edit
    end
  end

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to admin_test_question_answers_path
    else
      render :new
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_test_question_answers_path
  end

  private

  def answer_params
    params.require(:answer).permit(:correct, :body)
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: 'Question was not found'
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @test, @question, @answer], local: true do | form | %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
     <b> boolean </b> <br>
    <%= form.radio_button :correct, 'true' %> true <br />
    <%= form.radio_button :correct, 'false' %> false <br />
  </p>

  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body, id: :anwer_body %>
  </p>

  <p> <%= form.submit %> </p>
<% end %>

app/views/admin/answers/edit.html.erb
<%= render "form" %>
<%= link_to "Back", admin_test_question_answers_path %>

app/views/admin/answers/index.html.erb
<h1>Answers</h1>

<%= render 'shared/errors', resource: @answer %>

<p><%= link_to 'Create answer', new_admin_test_question_answer_path %></p>

<table class="table">
    <tr>
      <th>Answers</th>
    </tr>
  <% @question.answers.each do |answer| %>
    <tr>
        <td><%= answer.body %></td>
        <td><%= answer.correct %></td>

        <td><%=link_to 'Show', admin_test_question_answer_path(@test, @question, answer) %></td>
        <td><%=link_to 'Edit', edit_admin_test_question_answer_path(@test, @question, answer) %></td>
        <td>
          <%= link_to 'Delete',
          admin_test_question_answer_path(@test, @question, answer),
          method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
  <% end %>
    </tr>
</table>

app/views/admin/answers/new.html.erb
<%= render "form" %>
<%= link_to "Back", admin_test_question_answers_path %>

app/views/admin/answers/show.html.erb
<%= @answer.body %>
<%= @answer.correct %>