config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  devise_for :admins, :controllers => { :sessions => "admins/sessions" }

  root to: 'tests#index'

  resources :badges, only: :index

  resources :tests, only: :index do
    resources :questions, shallow: :true

    member do
      post :start
    end
  end

  resources :feedbacks, only: [:create, :new]

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions do
        resources :answers
      end
    end

    resources :gists, only: :index
  end

end

app/models/admin.rb
class Admin < User

  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validate :max_answers
  validates :body, presence: true

  def max_answers
    errors.add(:base, "exceeds the maximum value of answers") if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :user
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :title, :pic_name, :rule, presence: true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :tests

  scope :sort_category, -> { where(title: :asc) }

  validates :title, presence: true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  validates :body, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user

  def character_limit
    truncate(question.body, length: 25)
  end

  def html_url
    "https://gist.github.com/#{gist_remote_id}"
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :gists, dependent: :destroy
  has_many :answers, dependent: :destroy

  validates :body, presence: true

end

app/models/test.rb
# frozen_string_literal: true

class Test < ApplicationRecord
  has_many :test_passages, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :users, through: :test_passages
  belongs_to :category
  belongs_to :creator, class_name: 'User', foreign_key: :creator_id

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  scope :join_categories, -> (category_name) {
    joins(:category).where('categories.title  = ?', category_name)
   }
  scope :category_collection, -> (category_title) {
    joins(:category).where('categories.title = ?', category_title)
  }

  scope :join_test_passages, -> (category_id, user) {
    joins(:test_passages).where('tests.category_id = ? and user_id = ?', category_id, user.id)
  }


  validates :title, :level, :category, :time, presence: true
  validates :level, numericality: { greater_than: 0 }
  validates :title, uniqueness: { scope: :level }

  def self.category_tests
    join_categories.order(title: :desc).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  CHECK_NUMBER = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  # validates :current_question, presence: true

  before_validation :before_validation_set_current_question, on: :create

  scope :tests_by_level, -> (level) {
      joins(:test).where('tests.level = ?', level)
    }

  def completed?
    current_question.nil?
  end

  def expired?
    timing <= 0
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    self.current_question = next_question
    save!
  end

  def correct_answers
    current_question.answers.correct
  end

  def all_questions
    all_questions = test.questions
  end

  def success?
    count_true_answers >= CHECK_NUMBER
  end

  def count_true_answers
    self.correct_questions.to_f / test.questions.count * 100
  end

  def timing
    @start_time = self.created_at
    @spend_time = Time.now.to_i - @start_time.to_i
    time_left = self.test.time.to_i - @spend_time.to_i / 60
  end

  private

  def before_validation_set_current_question
    self.current_question = all_questions.first if test.present?
  end

  def next_question
    x = all_questions.find_index(current_question)
    all_questions[x + 1]
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count
    (correct_answers_count == correct_answers.where(id: answer_ids).count)
  end

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_many :test_passages
  has_many :gists
  has_many :user_badges
  has_many :feedbacks
  has_many :badges, through: :user_badges
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: 'Test', foreign_key: :creator_id

  validates :email, format: { with: VALID_EMAIL_REGEX }, uniqueness: true, presence: true
  # validates :password, presence: true, if: Proc.new { |u| u.password_digest.blank? }
  validates :password, confirmation: true

  def tests_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    self.is_a?(Admin)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  before_action :find_test, only: [:start]

  def index
    @tests = Test.where(status: true)
  end

  def start
    if @test.questions.present?
      current_user.tests.push(@test)
      redirect_to current_user.test_passage(@test)
    else
      flash[:notice] = "Not enough questions"
      redirect_to tests_path
    end
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_date
    Date.today.year
  end

  def current_link_to_project
    link_to('Учебный проект в онайн-школе Thinknetica', 'https://github.com/TupoBanKai/test-guru', target: true )
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      'Edit question'
    else
      'Create new question'
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def flash_helper
    if flash[:alert]
      content_tag :p, flash[:alert], class: 'flash alert'
    end
  end

end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def set_style
    if @test_passage.success?
      "<p style='color:green'> #{@test_passage.count_true_answers} </p><p>You passed the test</p>"
    else
      "<p style='color:red'> #{@test_passage.count_true_answers} </p><p>You did not passed the test</p>"
    end
  end

end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "TestGuru", root_path, class: 'navbar-brand' %>
  <div class="nav nav-admin">

    <span class="nav-admin title"><%= I18n.t 'nav.status' %></span>

    <div class="nav-admin user">
      <%= I18n.t('welcome') %> <b class="nav-admin user-email"><%= current_user.email %></b> Guru
      <%= link_to I18n.t('button_logout'), destroy_user_session_path, method: :delete %>
    </div>
  </div>
</nav>

app/views/layouts/_footer.html.erb
<div id="push"></div>
<footer class="footer navbar-fixed-bottom">
  <div class="container">
    <nav>
      <p><%= current_date %></p>
      <p> Ряполов Валерий.</p>
      <p> <%= current_link_to_project %> </p>
      <p>
        <%= link_to 'Test-Guru', root_path%>
      </p>
    </nav>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
    <%= link_to 'TestGuru', tests_path, class: 'navbar-brand' %>

    <span class="navbar-text">
      <% if user_signed_in? %>
        <p class="nav user">
          Welcome, <b><%= current_user.email %></b> guru |
          <%= link_to I18n.t('button_logout'), user_session_path, method: :delete %>
        </p>
        <p><%= link_to I18n.t('create_feedback'), new_feedback_path %></p>
      <% else %>
      <%= link_to "Login", new_session_path(resource_name) %>
      <%= link_to "Sign up", new_registration_path(resource_name) %>
    <% end %>
    </span>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Panel | TestGuru</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/nav' %>
    <%= render 'shared/flash' %>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fir=no">

    <title>TestGuru</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/nav" %>
    <%= render 'shared/flash' %>

    <div class="container">
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
    <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
      <h2>
        <%= t('.header', count: resource.errors.count) %>:
      </h2>

      <ul>
          <% resource.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    <% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, message, class: "#{key}"%>
<% end %>

app/views/shared/_nav.html.erb
<nav class = "navbar navbar-light bg-light">
  <%= link_to "TestGuru", tests_path, class: 'navbar-brand' %>

  <span class = "navbar-text">
    <% if user_signed_in? %>
      Welcome, <b><%= current_user.email %></b> guru |
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      <p><%= link_to I18n.t('create_feedback'), new_feedback_path %></p>
      <% if current_user.admin? %>
        <%= link_to "Admins's panel", admin_tests_path %>
      <% end %>
    <% else %>
      <%= link_to "Login", new_session_path(resource_name) %>
      <%= link_to "Sign up", new_registration_path(resource_name) %>
    <% end %>
  </span>
</nav>